name: Build APK (ARM64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'  # Updated to the suggested version
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build APK for ARM64
      run: flutter build apk --release --target-platform=android-arm64
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk-arm64
        path: build/app/outputs/flutter-apk/app-release.apk