name: Build APK (ARM64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build APKs (Split per ABI)
      run: flutter build apk --release --split-per-abi
    
    - name: Upload ARM64 APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk-arm64
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk